# Dataset configuration file for the datasets
# See README.md for more details

############ Corresondence Datasets ############

SPair-71k:
  path: "/export/compvis-nfs/group/datasets/SPair-71k"
  random_sampling: true

PF-WILLOW:
  path: "/data/PF-WILLOW"
  random_sampling: true

CUB-200-2011:
  path: "/data/CUB_200_2011"
  num_samples: 1000
  random_sampling: true

S2K:
  path: "/export/home/ffundel/DistillDIFT/data/PASCAL-Part"
  only_non_unique: true

CO3D:
  path: "/export/home/ffundel/co3d"
  random_sampling: true

############ Image Datasets ############

ImageNet:
  path: "/export/group/datasets/ILSVRC"
  random_sampling: true
  normalize_image: true

COCO:
  #path: "/export/group/datasets/coco"
  path: "/export/compvis-nfs/group/datasets/coco"
  embeddings_path: "/export/home/ffundel/DistillDIFT/cache/COCO_embeddings.pth"
  random_sampling: true
  num_samples: 24000 #12000

PASCALPart:
  path: "/export/group/datasets/PASCAL-Part"
