# Dataset configuration file for the datasets
# See README.md for more details

############ Corresondence Datasets ############

SPair-71k:
  path: "/export/group/datasets/SPair-71k"
  random_sampling: true

PF-WILLOW:
  path: "/export/home/ra63des/DistillDIFT/data/PF-WILLOW"
  random_sampling: true

CUB-200-2011:
  path: "/export/home/ra63des/DistillDIFT/data/CUB_200_2011"
  num_samples: 1000
  random_sampling: true

S2K:
  path: "/export/group/datasets/PASCAL-Part"
  only_non_unique: true

############ Image Datasets ############

ImageNet:
  path: "/export/group/datasets/ILSVRC"
  random_sampling: true
  normalize_image: true

COCO:
  path: "/export/group/datasets/coco"
  embeddings_path: "/export/scratch/ra63des/cache/COCO_embeddings.pth"
  random_sampling: true
  num_samples: 12000

PASCALPart:
  path: "/export/group/datasets/PASCAL-Part"

############ 3D Datasets ############

CO3D:
  path: "/export/group/datasets/co3d"
  random_sampling: true