# Configuration file for the models
# See README.md for more details

############ Replicate ############

hedlin:
  image_size: [512, 512]
  batch_size: 1
  grad_enabled: true
  image_range: [0, 1]

tang:
  image_size: [768, 768]
  batch_size: 1

zhang:
  image_size: [960, 960]
  batch_size: 1

luo:
  image_size: [224, 224]
  batch_size: 16
  drop_last_batch: true

############ Diffusion ############

diff_sd1-5:
  image_size: [768, 768]
  batch_size: 32
  model: 'runwayml/stable-diffusion-v1-5'
  layers: [0, 3, 5, 8, 11, 13, 15]
  step: 201

diff_sd2-1:
  image_size: [768, 768]
  batch_size: 32
  model: 'stabilityai/stable-diffusion-2-1'
  layers: [0, 3, 5, 8, 11, 13, 15]
  step: 261

diff_sdxl:
  image_size: [1024, 1024] #[768, 768]
  batch_size: 16 #32
  model: "stabilityai/stable-diffusion-xl-base-1.0"
  layers: [0, 1, 2, 4, 5, 7, 9, 11]
  step: 201 #101

############ DINO ############

dinov1_s8:
  image_size: [224, 224]
  batch_size: 32
  version: 1
  model_size: 's'
  patch_size: 8
  registers: false
  image_range: [0, 1]
  layers: [2, 4, 6, 9, 10, 11]

dinov2_b14:
  image_size: [840, 840]
  batch_size: 64
  version: 2
  model_size: 'b'
  patch_size: 14
  registers: false
  image_range: [0, 1]
  layers: [2, 4, 6, 9, 10, 11]

dinov2_b14_reg:
  image_size: [840, 840]
  batch_size: 64
  version: 2
  model_size: 'b'
  patch_size: 14
  registers: true
  image_range: [0, 1]
  layers: [2, 4, 6, 9, 10, 11]

dinov2_large:
  image_size: [840, 840]
  batch_size: 64
  version: 2
  model_size: 'l'
  patch_size: 14
  registers: false
  image_range: [0, 1]
  layers: [23]

############ OpenCLIP ############

clip:
  image_size: [336, 336]
  batch_size: 64
  image_range: [0, 1]
  layers: [2, 4, 6, 9, 10, 11]

############ MAE ############

# download weights using the following command:
# wget https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_large.pth

mae:
  image_size: [224, 224]
  batch_size: 32
  model_path : '/export/home/ra63des/.cache/mae_visualize_vit_large.pth'
  arch: 'mae_vit_large_patch16' # mae_vit_large_patch16, mae_vit_huge_patch14
  patch_size: 16 # 14, 16
  image_range: [0, 1]
  layers: [3, 8, 13, 18, 23, 24, 26, 29, 31]

############ Depth ############

zoedepth:
  image_size: [512, 384]
  batch_size: 32
  version: 'NK' # N, K, NK
  image_range: [0, 1]
  layers: [0, 8, 10, 16, 23, 25, 27, 29]

############ GAN ############

gan_lafite:
  image_size: [256, 256]
  batch_size: 1
  model_path : '/export/scratch/ra63des/lafite'
  layers: null
  image_range: [0, 1]
  grad_enabled: true