# Configuration file for the models
# See README.md for more details

hedlin:
  image_size:
    - 512
    - 512
  batch_size: 1
  grad_enabled: true

tang:
  image_size:
    - 768
    - 768
  batch_size: 1

zhang:
  image_size:
    - 960
    - 960
  batch_size: 1

luo:
  image_size:
    - 224
    - 224
  drop_last_batch: true

dinov1_s16:
  image_size:
    - 960
    - 960
  batch_size: 16
  version: 1
  model_size: 's'
  patch_size: 16
  layers: 11