# Configuration file for the models
# See README.md for more details

############ Single Teacher ############

single_first_stage:
  teacher_name: "add_xl"
  teacher_config:
    image_size: [224, 224]
  student_name: "distilldift_1"
  student_config:
    image_size: [224, 224]
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001