# Configuration file for the models
# See README.md for more details

############ Training ############

dinov2:
  image_size: [336, 336]
  batch_size: 64
  version: 2
  model_size: 'b'
  patch_size: 14
  registers: true
  image_range: [0, 1]
  layers: [11]

  batch_size: 32
  num_epochs: 25
  learning_rate: 0.001
  gradient_accumulation_steps: 1
  mode: "train"
  similarity_method: "softmax"
  loss_function: "cross_entropy"

############ Distillation ############

distilldift_1:
  teacher_name: "combination_add"
  image_size: [518, 518]
  teacher_config:
    image_range: [0, 1]
    model1: 'diff_add'
    model2: 'dinov2_b14_reg'
    model1_config:
      model: "stabilityai/sdxl-turbo"
      layers: [1]
      step: 101
    model2_config:
      version: 2
      model_size: 'b'
      patch_size: 14
      registers: true
      layers: [11]
  student_name: "distilldift"
  student_config:
    model: "stabilityai/sdxl-turbo"
    #layers: [1]
    step: 101
    weights: null
    rank: 16
  batch_size: 2 #4 # 8
  num_epochs: 5
  learning_rate: 0.001
  gradient_accumulation_steps: 1
  strategy: "full"
