weights_path: /export/home/ra63des/DistillDIFT/replicate/luo/weights/aggregation_network.pt
diffusion_mode: inversion
output_resolution: 64
batch_size: 16
prompt: ''
negative_prompt: ''
guidance_scale: -1
flip_timesteps: false
save_timestep:
- 49
- 45
- 40
- 35
- 30
- 25
- 20
- 15
- 10
- 5
- 0
num_timesteps: 50
model_id: runwayml/stable-diffusion-v1-5
load_resolution: 224
